### ISSUE TITLE
gas parser: "error: unexpected end of file in string" for valid file

### ISSUE THREAD

**Issue by Scarletts** [yasm/yasm#82]
~~~
$ yasm -p gas -o skel.o skel.s  
skel.s:3088: error: unexpected end of file in string
$ as -o skel.o skel.s 
$ file skel.o
skel.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
~~~

gas can assemble this, but yasm 1.3.0 with the gas parser fails.

[skel.s](https://github.com/yasm/yasm/files/632372/skel.txt) is attached.

**Comment by Scarletts** [comment]
fixed by #81

**Comment by colincross** [comment]
#81 fixes the issue for:
```
	.ascii "/*"
```
but still fails for:
```
	.ascii /*comment*/ "/*"
```

This is likely related to the warning produced by clang version 22.0.2 introduced in #81:
```
modules/preprocs/gas/gas-preproc.c:1065:53: error: loop will run at most once (loop increment never executed) [-Werror,-Wunreachable-code-loop-increment]
 1065 |     for (c = line, s = line; (c = strstr(c, "/*")); s = c) {
      |                                                     ^~~~~
```
